### ISSUE TITLE
Implementing Telegram Bot

### ISSUE THREAD

**Issue by Palmerg4** [fifikobayashi/FurucomboWatcher#3]
What would be the best method of implementing the telegram bot output? Is it possible to store this information in a separate document? Any info would be greatly appreciated, thanks for the Furucombo Watcher.

**Comment by arsenikt** [comment]
Just use [node-telegram-bot-api](https://github.com/yagop/node-telegram-bot-api).
For example https://gist.github.com/arsenikt/0485026b62e811922721a476c63f2229
